### ISSUE TITLE
Issue about the pre-trained model

### ISSUE THREAD

**Issue by chenbinghui1** [littleredxh/DREML#1]
thanks for your contributions first!, but I think it is not fair to compare with other SOTA methods without the same CNN model, i.e. GoogleNet V1. In paper, you use Resnet-18 and V3. So could you provide the results on model Googlenet V1？

**Comment by littleredxh** [comment]
Thank you for your remind. I check the pytorch model zoo, the GoogleNet there is GoogleNet V3. I have used a pytorch version of GoogleNet V1 and tested it on the CAR 196 dataset. The recall@1 is 84.2%, which is close to my SOFT result (Inception V3 and Resnet18) in the paper and better than the other SOTA methods. I will update paper for the result with GoogleNet V1 later.
