### ISSUE TITLE
The output dimension for the retrieval.

### ISSUE THREAD

**Issue by PkuRainBow** [littleredxh/DREML#4]
Really interesting work.

I am wondering the final embedding dimension in your method.

For example, the table 

![image](https://user-images.githubusercontent.com/4639578/47978448-e5feea80-e0f8-11e8-9ddc-fd7831321735.png)

According to the discription in the paper, I guess that the final embedding dimension of  DREML (R,12,48) is 48 X 512 = 24576.

(R, 12, 48) means that you employ 48 network, and each network  employs 12 group labels.

Similarly, it seems that you employ much higher dimension on the Stanford-Products dataset,

![image](https://user-images.githubusercontent.com/4639578/47978497-2d857680-e0f9-11e8-97e2-5174fcf3d25a.png)

So does DREML (R,192,48) employ 48 X 512 = 24576-D feature embeddings?

**Comment by littleredxh** [comment]
For CUB and CAR, each network output dimension is 12 and the total dimension is 12 x 48=576
For In-shop Clothes dataset, each network output dimension is 192 and the total dimension is 192 x 48=9216.

It looks like the method employs a high dimension(the only reason is to show the best result). But, a few networks can also achieve some nice records. In figure 3, the left graph shows that if you choose the right size for the meta-class, 6 networks can achieve very high R@1 accuracy.

[edit: replaced asterix with x to make comment more readable]
