### ISSUE TITLE
Evaluation protocol for PKU VehicleID dataset

### ISSUE THREAD

**Issue by asanakoy** [littleredxh/DREML#5]
Could you please share the routine for the evaluation on PKU VehicleId dataset? 
We want to have exactly the same procedure in our paper to be fully comparable with your results.

**Comment by littleredxh** [comment]
You can the Recall.ipynb file to evaluated your result

**Comment by asanakoy** [comment]
So it means that you have exactly the same evaluation procedure for StanfordCars and  PKU VehicleId dataset? 
I'm asking that, because PKU Vehicke Id has specific train/test splits and a different evaluation protocol described in the original paper.

**Comment by littleredxh** [comment]
Yes, I know that. The origin paper didn't release the evaluation code. I followed the idea in the BIER paper to do the recall test.
